### ISSUE TITLE
Improve /clus/tree/master/R/apps/testApp

### ISSUE THREAD

**Issue by TylerMuhly** [bcgov/clus#10]
1. add caribou population data output (and trend?) using ggplot
2. add spatial caribou telemetry location and/or home range data
3. add other types of protected areas (e.g., parks)
4. cut disturbance, allow user to adjust cutblock age
5. add spatial fire/cut data
6. update with RSF, possibly new climate data (when complete)
7. calculate disturbance area/range; allow user to adjust disturbance buffers

**Comment by TylerMuhly** [comment]
Feedback from regional staff: 
'Would be good to see other metrics that make comparison easier between herds ie. Km/km2 of road, proportion of area in cutblock/fire'

**Comment by KyleLochhead** [comment]
**1. done**
2. open -add spatial caribou telemetry location and/or home range data
3. open - add other types of protected areas (e.g., parks)
**4. done**
5 open - add spatial fire/cut data
6. open - update with RSF, possibly new climate data (when complete)
**7. done**

Ported the beta version to: https://bcgov-clus.shinyapps.io/beta/

**Comment by TylerMuhly** [comment]
More feedback from staff:

1. Crashed when calculating disturbance for Chase herd.
2. Add data sources, dates.
3. Add buffer for fires?
4. Add capability to download csv of disturbance figure data

**Comment by KyleLochhead** [comment]
Deprecated Scenario CLUS app
