### ISSUE TITLE
Make default values for zone rasters as a value (e.g., -99) instead of NA

### ISSUE THREAD

**Issue by TylerMuhly** [bcgov/clus#112]
Zone parameters are created with "NA" as default for areas with no value (no defined zone). It might be better to make it a value (e.g., -99) to allow functionality in using zones as constrains or priority harvest areas (rasters with NA values will not work as a priority area).

**Describe the solution you'd like**
When creating a raster parameter, make it standard practice to define a value, e.g., 
ALTER TABLE pixels ADD COLUMN zone1 INTEGER DEFAULT -99

The idea needs some consideration of implications and some testing before making a switch.

**Comment by KyleLochhead** [comment]
closing for now ... we can revisit once more complicated zoning priorities are considered
