### ISSUE TITLE
roadCLUS: not simulating roads to all landings using the "pre" method

### ISSUE THREAD

**Issue by TylerMuhly** [bcgov/clus#345]
**The bug**
When I use "pre" method to simulate the roads in forestryCLUS, I noticed it wasn't simulating roads to new cutblocks. First, I noticed that the amount of roads being estimated in disturbanceCalcCLUS was the same each year (see table screenshot below). I then checked the harvestBlocks and road 'status' and 'year' raster outputs and noticed that roads were not being simulated to new harvest blocks (see image screen shot below; green-yellow are blocks, red are roads).

**To Reproduce**
1. Run this scenario (https://github.com/bcgov/clus/blob/main/R/scenarios/central_group/bau_20220721.Rmd) with roadMethod = 'pre'. Can do this for 1 or 2 intervals (times <- list(start = 0, end = 2)). Set the scenario = data.table (name = "road_test", description = "raid test.")
2.  Input and output data is here:  \\\spatialfiles2.bcgov\archive\FOR\VIC\HTS\ANA\PROJECTS\CLUS\road_test

**Expected behavior**
Roads to landings should be simulated.

**Screenshots**
![image](https://user-images.githubusercontent.com/34694298/181106944-149a900e-3bb3-4aa9-8bde-aaf3b6368203.png)

![image](https://user-images.githubusercontent.com/34694298/181106506-d086860e-74ff-43d4-81ff-5a61374a702d.png)

**Comment by KyleLochhead** [comment]
The future landings were not added to the pre-solve list of target landings. preSolve () { targets <- historic + future}

**Comment by KyleLochhead** [comment]
historic and future targets are added in the pre-solve now
