### ISSUE TITLE
README File mising

### ISSUE THREAD

**Issue by agehlers** [bcgov/clus#7]
Hi, could you please add a README file to your repo. All repositories in the BCGOV ORG should have a README file. Reference: https://github.com/bcgov/BC-Policy-Framework-For-GitHub/tree/master/BC-Gov-Org-HowTo and https://github.com/bcgov/BC-Policy-Framework-For-GitHub/blob/master/BC-Gov-Org-HowTo/Cheatsheet.md. Thank you.

**Comment by KyleLochhead** [comment]
ok thanks - added one
