### ISSUE TITLE
Error when schema exists in db, but no tables in schema

### ISSUE THREAD

**Issue by TylerMuhly** [bcgov/clus#88]
When a schema gets created as part of the uploaderCLUS it looks to see if the schema exists and whether there are tables in the schema to delete (Line 77, uploaderCLUS.R). However, if the schema exists, but there are no tables, it throws an error at Line 83. 

**To Reproduce**
1. Create an empty schema in the postgres database and make that the name of the schema (aoiName) in uploaderCLUS
2. Run the dataloaderCLUS module (with the uploaderCLUS settings as above)
3. See postgres error, "cannot execute DELETE...."

**Expected behavior**
Needs an if/else statement to look to see if the schema is empty, and if it is empty, insert the table, rather then try to delete it.

**Comment by KyleLochhead** [comment]
Looking into module specific uploading... rather than using uploaderCLUS to accomplish this

**Comment by KyleLochhead** [comment]
This was driven by errors during the db build. Each report for each module is checked before creating.
